// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBmWNlN5gbN_zUQrivRgh_RD5lViQJK8g',
    appId: '1:19865387604:web:b5bc658bd3b11a0a77a3c1',
    messagingSenderId: '19865387604',
    projectId: 'chat-app-59a64',
    authDomain: 'chat-app-59a64.firebaseapp.com',
    storageBucket: 'chat-app-59a64.appspot.com',
    measurementId: 'G-BNWC95F1ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy3b5Lf_e7hqZzLksoldtacS-kQRBl6Yc',
    appId: '1:19865387604:android:1c6b3738cd6c470d77a3c1',
    messagingSenderId: '19865387604',
    projectId: 'chat-app-59a64',
    storageBucket: 'chat-app-59a64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApo_kTxTWuDoAGIAnd_ufHhZi_rUOwAb4',
    appId: '1:19865387604:ios:69379606edc5b28077a3c1',
    messagingSenderId: '19865387604',
    projectId: 'chat-app-59a64',
    storageBucket: 'chat-app-59a64.appspot.com',
    iosClientId: '19865387604-v3ldpfrplb4pru6p29jh5f1q7sokvfos.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApo_kTxTWuDoAGIAnd_ufHhZi_rUOwAb4',
    appId: '1:19865387604:ios:d77a4540272a96b577a3c1',
    messagingSenderId: '19865387604',
    projectId: 'chat-app-59a64',
    storageBucket: 'chat-app-59a64.appspot.com',
    iosClientId: '19865387604-s83dbqc4f53eelphmju8cjeekavb4oua.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitChatApp.RunnerTests',
  );
}
